# Allows us to install G++13, so we can use an updated libstdc++ which provides more standard library features (C++20)
- name: Add GCC PPA
  become: True
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test

- name: Add LLVM APT Key
  become: True
  apt_key:
    url: https://apt.llvm.org/llvm-snapshot.gpg.key

# Allows us to install LLVM tools
- name: Add LLVM APT List
  become: True
  apt_repository:
    repo: deb http://apt.llvm.org/{{ ubuntu_release }}/ llvm-toolchain-{{ ubuntu_release }}-18 main
    filename: llvm

- name: Add CMake APT Key
  become: True
  apt_key:
    url: https://apt.kitware.com/keys/kitware-archive-latest.asc
    keyring: /usr/share/keyrings/kitware-archive-keyring.gpg

# Allows us to install CMake versions newer than 3.16
- name: Add CMake APT List
  become: True
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ {{ ubuntu_release }} main
    filename: kitware

- name: Install APT Packages
  become: True
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - cmake
      - ccache # Caches intermediate build files, speeds up compilation over time
      - ninja-build # Faster than make
      - clang-18
      - clangd-18
      - clang-tidy-18
      - clang-format-18
      - lld-18
      - lldb-18
      - gcc-13
      - g++-13

- name: Set G++ 13 as Default
  become: True
  alternatives:
    name: g++
    path: /usr/bin/g++-13
    link: /usr/bin/g++
    priority: 130

- name: Set GCC 13 as Default
  become: True
  alternatives:
    name: gcc
    path: /usr/bin/gcc-13
    link: /usr/bin/gcc
    priority: 130

- name: Set clangd 18 as Default
  become: True
  alternatives:
    name: clangd
    path: /usr/bin/clangd-18
    link: /usr/bin/clangd
    priority: 180

- name: Set LLD 18 as Default
  become: True
  alternatives:
    name: lld
    path: /usr/bin/lld-18
    link: /usr/bin/lld
    priority: 180

- name: Set clang-tidy 18 as Default
  become: True
  alternatives:
    name: clang-tidy
    path: /usr/bin/clang-tidy-18
    link: /usr/bin/clang-tidy
    priority: 180

- name: Set clang-format 18 as Default
  become: True
  alternatives:
    name: clang-format
    path: /usr/bin/clang-format-18
    link: /usr/bin/clang-format
    priority: 180
