- name: Install APT Packages
  become: True
  apt:
    cache_valid_time: 604800
    state: latest
    name:
      - zsh
      - curl # for fzf install

- name: Install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    version: master

- name: Copy .zshrc
  synchronize:
    # The trailing slash is very important here
    # It tells rsync to copy only the CONTENTS of the folder and not the folder itself
    # This is vital to make sure this works will any usernames
    src: files/config/
    dest: ~/
    recursive: true

- name: Install zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Install zsh-syntaxhighlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Clone fzf plugin repo
  git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf

- name: Install fzf plugin
  command: ~/.fzf/install --key-bindings --completion --no-update-rc --no-bash --no-fish

- name: Download the zoxide install script
  get_url:
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
    dest: /tmp/install_zoxide.sh
    mode: '0755'
    
- name: Install zoxide plugin 
  shell: sh /tmp/install_zoxide.sh

- name: Clean up the zoxide install script
  file:
    path: /tmp/install_zoxide.sh
    state: absent

- name: Use zsh as the default shell
  become: true
  command: chsh --shell /usr/bin/zsh {{ ansible_user_id }} 

