set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi

set -sg escape-time 10
set -g focus-events on
# set -g default-terminal "screen-256color"
# set -a terminal-features xterm:RGB

set -g history-limit 10000

set -g mouse on

# tmux.nvim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }
bind-key -n 'C-n' if-shell "$is_vim" 'send-keys C-n' { if -F '#{window_end_flag}' '' 'select-window -n' }
bind-key -n 'C-p' if-shell "$is_vim" 'send-keys C-p' { if 'test #{window_index} -gt #{base-index}' 'select-window -p' }

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'
bind-key -T copy-mode-vi 'C-n' if -F '#{window_end_flag}' '' 'select-window -n'
bind-key -T copy-mode-vi 'C-p' if 'test #{window_index} -gt #{base-index}' 'select-window -p'

# ui customization

set -g @theme_bg 'colour236'
set -g @theme_fg 'colour250'
set -g @theme_muted 'colour244'
set -g @theme_tab 'colour238'
set -g @theme_accent 'colour218'

set -g pane-active-border-style "bg=default,fg=#{@theme_accent}"
set -g pane-border-status top
set -g pane-border-format '#[fg=#{@theme_muted},bg=default] #{?pane_active,#[fg=#{@theme_accent}#,bold],#[fg=#{@theme_muted}]}#P #{pane_current_command} #[default]'
set -g pane-border-style "bg=default,fg=#{@theme_muted}"
set -g pane-border-lines single

set -g status-style "bg=#{@theme_bg},fg=#{@theme_fg}"
set -g status-left '[#S] '
set -g status-left-style "bg=#{@theme_bg},fg=#{@theme_fg}"

set -g status-right-length 180
set -g status-interval 30
set -g status-right '#[fg=#{@theme_fg},bg=#{@theme_bg}] #{=/-110/...;s~([^/]*opark[^/]*)~#[fg=#{@theme_accent},bg=#{@theme_bg},bold]\1#[fg=#{@theme_fg},bg=#{@theme_bg},nobold]~:pane_current_path} #[fg=colour16,bg=#{@theme_muted}] %Y-%m-%d #[fg=colour16,bg=#{@theme_accent},bold] %H:%M #[default]'

set -g window-status-separator ''
set -g window-status-format "#[fg=#{@theme_fg},bg=#{@theme_tab}] #I:#W #[fg=#{@theme_tab},bg=#{@theme_bg}]"
set -g window-status-current-format "#[fg=colour16,bg=#{@theme_accent},bold] #I:#W #[fg=#{@theme_accent},bg=#{@theme_bg},nobold]"
