---
- hosts: all
  vars:
    ubuntu_release: jammy
  pre_tasks:
    - name: Update repositories
      become: True
      apt:
        update_cache: True
  roles:
    - role: python
      tags: python
    - role: cpp
      tags: cpp
    - role: node
      tags: node
    - role: rust
      tags: rust
