import = [
    "~/.config/alacritty/themes/catppuccin_macchiato.toml"
]

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

[font]

normal.family = "JetbrainsMonoNF"
bold.family = "JetbrainsMonoNF"
italic.family = "JetbrainsMonoNF"
bold_italic.family = "JetbrainsMonoNF"

